authors = [
    "XopoIII",
    "1axen",
]
description = "An IDL compiler written in Luau for ROBLOX buffer networking, with hardened inbound handling"
includes = [
    "README.md",
    "pesde.toml",
    "release/blink_pesde.luau",
]
license = "MIT"
name = "xopoiii/blink"
repository = "https://github.com/XopoIII/blink"
version = "0.20.0"

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
bin = "release/blink_pesde.luau"
environment = "lune"
